language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
# This runs test discovery on all modules with names ending '_tests'
  - python3 -m unittest discover -p '*_tests.py'
