language: python
python:
    #  - "3.2" # scipy requires python >= 3.4
    #  - "3.3"
    #  - "3.4" # networkx2.0 requires python >= 3.6
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
# This runs test discovery on all modules with names ending '_test'
  - python3 -m pytest -v
# command to silence email notifications
notifications:
  email: false
